### ISSUE TITLE
if "const char *string" == NULL : segfault (minor issue)

### ISSUE THREAD

**Issue by aautin** [cclaude42/ft_printf#1] opened 2024-01-28 16:29 UTC
```
int		ft_printf(const char *string, ...)
{
	va_list	args;
	int		i;
	int		printed;

        **if (string == NULL)
               return (-1);**        // this is the value returned by the original printf
	va_start(args, string);
	i = 0;
	printed = 0;
        while (string[i] != '\0') // here you check string[i] but you don't pre-check if string != NULL so you risk a segfault
        ...
}
```
It's a quite tricky case, I know, but yeah.
Very nice ft_printf otherwise ;)

**Comment by cclaude42** [comment] 2024-01-28 18:08
Good catch ! This will indeed segfault.

Interesting thing to note :
I coded this quite early on, but if my memory serves me right, I had actually thought about it. If I remember correctly : printf's null-handling is implementation specific, meaning certain versions on certain OSes will segfault, and others won't.

At the time, I followed "recode what's on my machine" implementation, but this is a bad idea. Even if printf segfaulted on my OS at the time, I shouldn't have reproduced potentially breaking behavior. Something important to note when following 42 standards : be careful of when _not_ to follow them :)

Also, be careful, I don't think my printf works with the current subject ; it changed a couple years ago ;)

Funny seeing my (bad) code from so long ago - and how far I've come since then. Cheers to you for giving me a blast to the past.

Thank you for your interest in my work, and good luck on your beginning curriculum !

**Comment by cclaude42** [comment] 2024-01-28 18:15
@aautin Actually, before I close this : why don't you fix it ? 😄 

I don't know if you've had the chance to do PRs yet, but if not, this could be good practice. Why don't you give it a try?

If you're up to it, the steps are roughly as follows :
- Fork my repository
- Change the part of the code you think should be improved
- Push your changes to your repository
- Create a pull request to my repository ; be careful to give a good title, description, and to tag this issue !
- I will review your PR, merge it into my code, and close this issue

You can then brag to your fellow students that you're an open-source enthusiast 😂 

There's good documentation by Github on all those steps, I suggest you read it. Being comfortable with cooperative git workflows is a valuable skill in the professional world.

Let me know if you're up to it.
Cheers, cclaude

**Comment by aautin** [comment] 2024-01-28 20:05
Hey @cclaude42 
I hope that my intervention didn't bother you, it was my first issue's creation.
Someone just created some of these in one of my repositories and I found that very kind and interesting : it helped me a lot.
I took notes on everything you said and I'll try to do a clean pull request on your project.

Yeah I noticed that you've got really better all over the years, I guess you can improve your printf hugely now haha.
I appreciate your advices and I hope I'll get used on most of GitHub functionalities.

**Comment by cclaude42** [comment] 2024-02-11 13:46
Merged PR that fixed this, closing issue.

Thanks @aautin for your work and good luck with your curriculum :)

**Closed as completed by cclaude42** 2024-02-11 13:46 UTC
